//! Command for updating a url source.

use shared_cqrs::command::domain::command::Command;

use crate::url_source::domain::value_objects::url_source_format::UrlSourceFormat;
use crate::url_source::domain::value_objects::url_source_id::UrlSourceId;
use crate::url_source::domain::value_objects::url_source_polling_interval::UrlSourcePollingInterval;
use crate::url_source::domain::value_objects::url_source_url::UrlSourceUrl;

/// Command that requests an update of an existing url source.
///
/// `updated_at` is generated by [`UrlSourceUpdater`] at execution time.
///
/// [`UrlSourceUpdater`]: super::url_source_updater::UrlSourceUpdater
pub struct UpdateUrlSourceCommand {
    pub id: UrlSourceId,
    pub url: UrlSourceUrl,
    pub format: UrlSourceFormat,
    pub polling_interval: UrlSourcePollingInterval,
}

impl Command for UpdateUrlSourceCommand {}
