//! Command for creating a sighting.

use std::time::SystemTime;

use shared_cqrs::command::domain::command::Command;

use crate::sighting::domain::value_objects::sighting_id::SightingId;
use crate::sighting::domain::value_objects::sighting_ioc_id::SightingIocId;
use crate::sighting::domain::value_objects::sighting_source_id::SightingSourceId;

/// Command that requests the creation of a new sighting.
///
/// `first_seen`, `last_seen`, `count`, `created_at` and `updated_at` are
/// generated by [`SightingCreator`] at execution time from the caller-supplied
/// `observed_at` timestamp.
///
/// [`SightingCreator`]: super::sighting_creator::SightingCreator
pub struct CreateSightingCommand {
    pub id: SightingId,
    pub ioc_id: SightingIocId,
    pub source_id: SightingSourceId,
    pub observed_at: SystemTime,
}

impl Command for CreateSightingCommand {}
