//! Command for observing an existing sighting.

use std::time::SystemTime;

use shared_cqrs::command::domain::command::Command;

use crate::sighting::domain::value_objects::sighting_id::SightingId;

/// Command that requests recording a new observation on an existing sighting.
///
/// `updated_at` is generated by [`SightingObserver`] at execution time.
///
/// [`SightingObserver`]: super::sighting_observer::SightingObserver
pub struct ObserveSightingCommand {
    pub id: SightingId,
    pub observed_at: SystemTime,
}

impl Command for ObserveSightingCommand {}
