//! Command for creating an ioc.

use shared_cqrs::command::domain::command::Command;

use crate::ioc::domain::value_objects::ioc_id::IocId;
use crate::ioc::domain::value_objects::ioc_type::IocType;
use crate::ioc::domain::value_objects::ioc_value::IocValue;

/// Command that requests the creation of a new ioc.
///
/// Timestamps are generated by [`IocCreator`] at execution time.
///
/// [`IocCreator`]: super::ioc_creator::IocCreator
pub struct CreateIocCommand {
    pub id: IocId,
    pub ioc_type: IocType,
    pub value: IocValue,
}

impl Command for CreateIocCommand {}
