//! Command for creating a url source.

use shared_cqrs::command::domain::command::Command;

use crate::url_source::domain::value_objects::url_source_format::UrlSourceFormat;
use crate::url_source::domain::value_objects::url_source_id::UrlSourceId;
use crate::url_source::domain::value_objects::url_source_polling_interval::UrlSourcePollingInterval;
use crate::url_source::domain::value_objects::url_source_url::UrlSourceUrl;

/// Command that requests the creation of a new url source.
///
/// Timestamps are generated by [`UrlSourceCreator`] at execution time.
///
/// [`UrlSourceCreator`]: super::url_source_creator::UrlSourceCreator
pub struct CreateUrlSourceCommand {
    pub id: UrlSourceId,
    pub url: UrlSourceUrl,
    pub format: UrlSourceFormat,
    pub polling_interval: UrlSourcePollingInterval,
}

impl Command for CreateUrlSourceCommand {}
